; file:     config.ini - vehicle-db config file
; author:   Ben Mullan (2025)


[database]
; the extension-less name of a *.sqlite file in /data
defaultDatabase = vehicles

; the name for a table within the above *.sqlite file
vehiclesTableName = allVehicles


[userInterface]
; the initial width-by-height of the main-window
mainWindowSize = 950x420

; render additional debugging artifacts
showDebuggingBorders = false